### ISSUE TITLE
Using hexo.locals as function throws

### ISSUE THREAD

**Issue by kuzzmi** [hexojs/hexo-livereload#4]
After installing I receive following:

```
ERROR Plugin load failed: hexo-livereload
TypeError: object is not a function
    at /home/kuzzmi/Projects/blog/node_modules/hexo-livereload/index.js:18:6
    at /home/kuzzmi/Projects/blog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/home/kuzzmi/Projects/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/kuzzmi/Projects/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/home/kuzzmi/Projects/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/home/kuzzmi/Projects/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/home/kuzzmi/Projects/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:175:16)
    at Async._drainQueues (/home/kuzzmi/Projects/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:185:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/kuzzmi/Projects/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

I changed this code:
```
hexo.locals({
  livereload_js: function(){
    return serverUrl + '/livereload.js';
  }
});
```
to this: 

```
hexo.locals.set('livereload_js', function(){
    return serverUrl + '/livereload.js';
});
```

No errors, but plugin is still not working.

I'm digging deeper to know what happens here, so if I find the solution before you, I'll make a pull request.

**Comment by celsomiranda** [comment]
The `hexo-server` architecture is completely different from the 2.8.x version. You can take a look in `hexo-browsersync` to figure out how it plugs into the server.

Also, this is pretty much deprecated in versions > 3.x so you should use browsersync instead.

**Comment by kuzzmi** [comment]
Hm... So LiveReload is not supported. I just don't want to switch to another LiveReload-analogue as I use LR everywhere. 
I'll take a look into `hexo-browsersync` sources, perhaps I'll figure out how to remake this plugin to work fine with current Hexo version.

**Comment by celsomiranda** [comment]
BrowserSync works out of the box, so you don't have to install anything besides that package.

It's cleaner than Livereload as no extension is required to use it, and a lot more powerful.

**Comment by kuzzmi** [comment]
Ok, thanks for information, I'll take a look.
